FROM hgfkeep/llm:hf-cuda11.8-torch11.4

RUN apt-get update && apt-get install -y zsh
RUN sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN sed -i 's/ZSH_THEME="robbyrbob"/ZSH_THEME="ys"/g' ~/.zshrc

COPY dev_requirements.txt /tmp/requirements.txt

COPY jupyter_lab_config.py /root/.jupyter/jupyter_lab_config.py

# 安装packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    net-tools 

# 安装开发库
RUN pip install --no-cache-dir -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt
    