FROM hgfkeep/llama:hf_torch_chat

RUN apt-get update && apt-get install -y zsh
RUN sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN sed -i 's/ZSH_THEME="robbyrbob"/ZSH_THEME="ys"/g' ~/.zshrc

COPY dev_requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt
RUN mkdir /etc/jupyter/ && wget -P /etc/jupyter/  https://raw.githubusercontent.com/Winowang/jupyter_gpu/master/jupyter_notebook_config.py && \
    wget -P /etc/jupyter/ https://raw.githubusercontent.com/Winowang/jupyter_gpu/master/custom.js

RUN apt-get install tmux vim

# COPY jupyter_lab_config.py /root/.jupyter/jupyter_lab_config.py
# COPY jupyter_notebook_config.json /root/.jupyter/jupyter_notebook_config.json
